# Generated by Django 4.1.7 on 2023-06-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourPieces', models.CharField(max_length=10, verbose_name='Часы')),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdayName', models.CharField(max_length=15, verbose_name='Дни недели')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.instructors')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.hours')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.weekdays')),
            ],
            options={
                'verbose_name': 'Запись на практику',
                'verbose_name_plural': 'Записи на практику',
            },
        ),
    ]
